export const siteConfig = {
  name: "Lumina UI",
  url: "https://luminaui.in",
  ogImage: {
    url: "/ogImg.png", 

    alt: "Lumina UI - Ready-to-Use UI Components for Next.js",
  },
  description:
    "Ready-to-Use UI Components for Next.js. Accelerate your project's growth with UI components that save time and elevate quality.",
  authors: [
    {
      name: "Rohit Kumar",
      url: "https://rohitk.me",
    },
    {
      name: "Aryan Pahuja",
      url: "https://aryan-pahuja.vercel.app",
    },
    {
      name: "Rohit Nayak",
      url: "https://x.com/rohitn_2312",
    },
    {
      name: "Murtaza Khan",
      url: "https://x.com/murtazakhan1910",
    },
  ],
  keywords: [
    "Lumina UI",
    "luminaui",
    "UI Components",
    "UI components",
    "Next.js components",
    "Tailwind components",
    "Next.js",
    "Tailwind CSS",
    "React",
    "Server Components",
    "Vercel",
    "Radix UI",
    "Design",
    "100xdevs",
    "web development",
    "web design",
    "bootstrap",
    "tailwind",
    "aceternity",
    "shadcn ui",
    "Accessible design",
    "Web development",
    "Frontend",
    "Design system",
    "100xdevs",
    "Accessible design",
    "Aceternity",
    "Bootstrap",
    "Design",
    "Design system",
    "Frontend",
    "Lumina UI",
    "Next.js",
    "Next.js components",
    "Radix UI",
    "React",
    "Shadcn UI",
    "Tailwind",
    "Tailwind CSS",
    "UI Components",
    "Vercel",
    "Web development",
    "Web design",
    "rohit kumar",
    "aryan pahuja",
    "murtaza khan",
    "rohit nayak"
  ],
  locale: "en-US",
  version: "1.0.0",
  license: "MIT",
};

export type SiteConfig = typeof siteConfig;
